### ISSUE TITLE
Animation Suspended

### ISSUE THREAD

**Issue by rild** [rild/android-activity-transition-test#1]
# What

Transition animation would not work well.
## Detail

When testing the app with actual equipment (Xperia Z3), UI animation seems to work wrongly.
# Error Log

```
E/ActivityThread: Performing stop of activity that is not resumed: {rimp.rild.com.android.android_activity_transition_test/rimp.rild.com.android.android_activity_transition_test.MainActivity}
                                                                                                      java.lang.RuntimeException: Performing stop of activity that is not resumed: {rimp.rild.com.android.android_activity_transition_test/rimp.rild.com.android.android_activity_transition_test.MainActivity}
                                                                                                          at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3412)
                                                                                                          at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3493)
                                                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:149)
                                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:211)
                                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5335)
                                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

```
W/art: Suspending all threads took: 6.515ms
```

**Comment by rild** [comment]
```
E/ActivityThread: Performing stop of activity that is not resumed: {rimp.rild.com.android.android_activity_transition_test/rimp.rild.com.android.android_activity_transition_test.MainActivity}
                                                                                                      java.lang.RuntimeException: Performing stop of activity that is not resumed: {rimp.rild.com.android.android_activity_transition_test/rimp.rild.com.android.android_activity_transition_test.MainActivity}
                                                                                                          at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3412)
                                                                                                          at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3493)
                                                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:149)
                                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:211)
                                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5335)
                                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```
